In [5]:
from numpy import *
arr = array([2, 3, 4, 5, 6])
print(arr)

[2 3 4 5 6]


In [8]:
# Create one array using another array : And Copy the data from one array to another :
from numpy import *
arr1 = array([3, 4, 5, 6])
arr2 = arr1
print(arr2)
print(type(arr2)) # Print type of array 3

[3 4 5 6]
<class 'numpy.ndarray'>


In [1]:
# How to add 5 in each item of any array :
from numpy import *
arr1 = array([1,2,3,4,5])
arr1 = arr1 + 5
print(arr1)
arr2 = arr2 - 1
print(arr2)
arr3 = arr3 * 5
print(arr3)
arr4 = arr4 / 2
print(arr4)

[ 6  7  8  9 10]
[5 6 7 8 9]
[25 30 35 40 45]
[12.5 15.  17.5 20.  22.5]


In [3]:
# How to add two array : Never add the different length of array :
from numpy import *
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
arr3 = arr1 + arr2
print(arr3)

[ 7  9 11 13 15]


In [12]:
# Get the sin value of any array :
from numpy import *
arr = array([0, 30, 45, 60, 90])
print("sin = ", sin(arr))
print("cos = ", cos(arr))
print("tan = ", tan(arr))
# print(sec(arr)) --> Not Defined
# print(cosec(arr)) --> Not Defined
# print(cot(arr)) --> Not Defined

sin =  [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
cos =  [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
tan =  [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [13]:
# Sum of any array :
from numpy import *
arr = array([1,2,3,4,5])
print(sum(arr))

15


In [5]:
# How to calculate MIN, Max, Log and Square Root value of a array : 
from numpy import *
arr = array([1,2,3,4,5])
print("Minimum value of array : ", min(arr))
print("Maximum value of array : ", max(arr))
print("Log value of array : ", log(arr)) // Return the value on base e
print("Square root value of array : ", sqrt(arr))

Minimum value of array :  1
Maximum value of array :  5
Log value of array :  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Square root value of array :  [1.         1.41421356 1.73205081 2.         2.23606798]


In [10]:
# How to demonstrate the Concatenation of array : 
from numpy import *
arr1 = array([1,2,3])
arr2 = array([4,5,6])
print(concatenate([arr1,arr2]))

[1 2 3 4 5 6]


In [6]:
# How to create 2D array :
from numpy import * 
# arr = array([ [1,2,3], [4,5,6] ])
arr = array([
            [1,2,3],
            [4,5,6]
            ])
print(arr)
print("Array Type =", arr.dtype) # Used to check array type
print("Dimension =", arr.ndim) # Used to check dimension of a array
print("Shape =", arr.shape) # Used to check the shape of the array
print("Size =", arr.size) # Used to check size of the array : it return the total element of the array

[[1 2 3]
 [4 5 6]]
Array Type = int64
Dimension = 2
Shape = (2, 3)
Size = 6
